"""Convenience exports for node base classes and marker mixins."""

from cuvis_ai.node.anomaly import (
    DeepSVDDProjection,
    LADGlobal,
    RXGlobal,
    RXPerBatch,
    ZScoreNormalizerGlobal,
)
from cuvis_ai.node.anomaly_visualization import (
    AnomalyMask,
    BBoxesOverlayNode,
    ChannelSelectorFalseRGBViz,
    ChannelWeightsViz,
    ImageArtifactVizBase,
    MaskOverlayNode,
    RGBAnomalyMask,
    ScoreHeatmapVisualizer,
    TrackingOverlayNode,
    TrackingPointerOverlayNode,
)
from cuvis_ai.node.blob_detector import BlobDetector
from cuvis_ai.node.channel_mixer import ConcreteChannelMixer, LearnableChannelMixer
from cuvis_ai.node.channel_selector import (
    CameraEmulationFalseRGBSelector,
    ChannelSelectorBase,
    CIETristimulusRGBSelector,
    CIRedEdgeSelector,
    CIRSelector,
    EVI2Selector,
    EVISelector,
    FastRGBSelector,
    FixedWavelengthSelector,
    GNDVISelector,
    HighContrastSelector,
    MCARISelector,
    MSAVISelector,
    NBRSelector,
    NDRESelector,
    NDVISelector,
    NDWISelector,
    NormMode,
    PRISelector,
    RangeAverageFalseRGBSelector,
    SAVISelector,
    SoftChannelSelector,
    SupervisedCIRSelector,
    SupervisedFullSpectrumSelector,
    SupervisedSelectorBase,
    SupervisedWindowedSelector,
    TopKIndices,
)
from cuvis_ai.node.clustering import GaussianMixtureClusterer, KMeansClusterer
from cuvis_ai.node.colormap import ClassMapToRGB, ScalarHSVColormapNode
from cuvis_ai.node.compositing import (
    ImageConcatenator,
    InsetComposer,
    LabelOverlay,
    LegendStrip,
    ROIZoomNode,
    TitleOverlay,
)
from cuvis_ai.node.conversion import DecisionToMask
from cuvis_ai.node.deciders import (
    BinaryDecider,
    MultiRangeSlicer,
    QuantileBinaryDecider,
    TwoStageBinaryDecider,
)
from cuvis_ai.node.dimensionality_reduction import PCA, TrainablePCA
from cuvis_ai.node.image_file import PngWriter
from cuvis_ai.node.json_file import (
    CocoTrackBBoxWriter,
    CocoTrackMaskWriter,
    DetectionCocoJsonNode,
    DetectionJsonReader,
    TrackingResultsReader,
)
from cuvis_ai.node.labels import BinaryAnomalyLabelMapper
from cuvis_ai.node.losses import (
    CrossEntropyLoss,
    DiceLoss,
    DistinctnessLoss,
    ForegroundContrastLoss,
)
from cuvis_ai.node.mask_ops import (
    ClassMapRobustifier,
    LabelOffset,
    MajorityVoteByBlob,
    MaskRobustifier,
    MaskToBBoxKalman,
    NearestLabelFill,
)
from cuvis_ai.node.morphology import ShapeMorphology
from cuvis_ai.node.normalization import (
    DisplayNormalizer,
    IdentityNormalizer,
    MinMaxNormalizer,
    PercentileNormalizer,
    SigmoidNormalizer,
)
from cuvis_ai.node.numpy_file import NpyReader, NumpyFeatureWriterNode
from cuvis_ai.node.occlusion import (
    OcclusionNodeBase,
    PoissonCubeOcclusionNode,
    PoissonOcclusionNode,
    SolidOcclusionNode,
)
from cuvis_ai.node.patch_inference import ClassMapAccumulator, PatchSampler
from cuvis_ai.node.pipeline_visualization import (
    CubeRGBVisualizer,
    PCAVisualization,
    PipelineComparisonVisualizer,
)
from cuvis_ai.node.preprocessors import (
    BandpassByWavelength,
    BBoxRoiCropNode,
    ChannelNormalizeNode,
    SaturatedPixelDetector,
    SpatialRotateNode,
)
from cuvis_ai.node.pretreatments import (
    ContinuumRemoval,
    Logarithm,
    MeanCenter,
    SavitzkyGolay,
    SNVCorrection,
    SpectralDerivative,
    UnitVarianceScaling,
)
from cuvis_ai.node.prompts import BBoxPrompt, MaskPrompt, PointPrompt, TextPrompt
from cuvis_ai.node.segmentation import IntensityThresholdSegmenter
from cuvis_ai.node.spectral_angle_mapper import SpectralAngleMapper
from cuvis_ai.node.spectral_extractor import (
    BBoxSpectralExtractor,
    MaskedMeanSpectrum,
    SignaturesToReferences,
    SpectralSignatureExtractor,
)
from cuvis_ai.node.spectrum_plot import SpectraPlot, SpectrumPlotNode
from cuvis_ai.node.svm import OneClassSVMDetector
from cuvis_ai.node.unmixing import NMFUnmixing, NNLSUnmixing
from cuvis_ai.node.video import (
    ToImage,
    ToVideoNode,
    VideoFrameDataModule,
    VideoFrameDataset,
    VideoFrameNode,
    VideoIterator,
)

__all__ = [
    "AnomalyMask",
    "BandpassByWavelength",
    "BBoxesOverlayNode",
    "BBoxRoiCropNode",
    "BBoxSpectralExtractor",
    "BBoxPrompt",
    "BinaryAnomalyLabelMapper",
    "ChannelNormalizeNode",
    "CameraEmulationFalseRGBSelector",
    "ChannelSelectorBase",
    "ChannelSelectorFalseRGBViz",
    "ChannelWeightsViz",
    "CIETristimulusRGBSelector",
    "CIRSelector",
    "ClassMapRobustifier",
    "ClassMapToRGB",
    "FastRGBSelector",
    "ConcreteChannelMixer",
    "CrossEntropyLoss",
    "CubeRGBVisualizer",
    "DetectionCocoJsonNode",
    "DetectionJsonReader",
    "DecisionToMask",
    "DiceLoss",
    "DisplayNormalizer",
    "DistinctnessLoss",
    "FixedWavelengthSelector",
    "ForegroundContrastLoss",
    "HighContrastSelector",
    "IdentityNormalizer",
    "ImageArtifactVizBase",
    "ImageConcatenator",
    "InsetComposer",
    "LabelOverlay",
    "LabelOffset",
    "LearnableChannelMixer",
    "LegendStrip",
    "ROIZoomNode",
    "TitleOverlay",
    "MaskedMeanSpectrum",
    "MaskOverlayNode",
    "MaskPrompt",
    "PointPrompt",
    "MaskRobustifier",
    "MaskToBBoxKalman",
    "NearestLabelFill",
    "TextPrompt",
    "MinMaxNormalizer",
    "NDVISelector",
    "NormMode",
    "NumpyFeatureWriterNode",
    "NpyReader",
    "OcclusionNodeBase",
    "PngWriter",
    "PoissonCubeOcclusionNode",
    "PoissonOcclusionNode",
    "PCA",
    "PCAVisualization",
    "PercentileNormalizer",
    "PipelineComparisonVisualizer",
    "RangeAverageFalseRGBSelector",
    "RGBAnomalyMask",
    "ScoreHeatmapVisualizer",
    "ScalarHSVColormapNode",
    "SigmoidNormalizer",
    "SolidOcclusionNode",
    "SoftChannelSelector",
    "SpatialRotateNode",
    "SpectraPlot",
    "SpectralAngleMapper",
    "SpectrumPlotNode",
    "ToImage",
    "SupervisedCIRSelector",
    "SupervisedFullSpectrumSelector",
    "SupervisedSelectorBase",
    "SupervisedWindowedSelector",
    "ToVideoNode",
    "TopKIndices",
    "VideoFrameDataModule",
    "VideoFrameDataset",
    "VideoFrameNode",
    "VideoIterator",
    "CocoTrackMaskWriter",
    "CocoTrackBBoxWriter",
    "TrackingPointerOverlayNode",
    "TrackingOverlayNode",
    "TrackingResultsReader",
    "TrainablePCA",
    "BinaryDecider",
    "DeepSVDDProjection",
    "LADGlobal",
    "QuantileBinaryDecider",
    "RXGlobal",
    "RXPerBatch",
    "TwoStageBinaryDecider",
    "ZScoreNormalizerGlobal",
    "SavitzkyGolay",
    "ContinuumRemoval",
    "SpectralDerivative",
    "SNVCorrection",
    "Logarithm",
    "MeanCenter",
    "UnitVarianceScaling",
    "EVISelector",
    "EVI2Selector",
    "SAVISelector",
    "MSAVISelector",
    "NDWISelector",
    "NBRSelector",
    "GNDVISelector",
    "NDRESelector",
    "CIRedEdgeSelector",
    "MCARISelector",
    "PRISelector",
    "NNLSUnmixing",
    "NMFUnmixing",
    "ShapeMorphology",
    "KMeansClusterer",
    "GaussianMixtureClusterer",
    "OneClassSVMDetector",
    "SaturatedPixelDetector",
    "MultiRangeSlicer",
    "IntensityThresholdSegmenter",
    "BlobDetector",
    "MajorityVoteByBlob",
    "SignaturesToReferences",
    "SpectralSignatureExtractor",
    "PatchSampler",
    "ClassMapAccumulator",
]
