# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cuvis_ai.grpc.v1 import cuvis_ai_pb2 as cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2


class CuvisAIServiceStub(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/CreateSession',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/CloseSession',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.Train = channel.unary_stream(
                '/cuvis_ai.v1.CuvisAIService/Train',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.TrainRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.GetTrainStatus = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/GetTrainStatus',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainStatusRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainStatusResponse.FromString,
                _registered_method=True)
        self.GetTrainingCapabilities = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/GetTrainingCapabilities',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainingCapabilitiesRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainingCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ValidateTrainingConfig = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/ValidateTrainingConfig',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.ValidateTrainingConfigRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.ValidateTrainingConfigResponse.FromString,
                _registered_method=True)
        self.GetPipelineInputs = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/GetPipelineInputs',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineInputsRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineInputsResponse.FromString,
                _registered_method=True)
        self.GetPipelineOutputs = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/GetPipelineOutputs',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineOutputsRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineOutputsResponse.FromString,
                _registered_method=True)
        self.GetPipelineVisualization = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/GetPipelineVisualization',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineVisualizationRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineVisualizationResponse.FromString,
                _registered_method=True)
        self.Inference = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/Inference',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.InferenceRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/SaveCheckpoint',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.SaveCheckpointResponse.FromString,
                _registered_method=True)
        self.LoadCheckpoint = channel.unary_unary(
                '/cuvis_ai.v1.CuvisAIService/LoadCheckpoint',
                request_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.LoadCheckpointRequest.SerializeToString,
                response_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.LoadCheckpointResponse.FromString,
                _registered_method=True)


class CuvisAIServiceServicer(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def CreateSession(self, request, context):
        """Session Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Training
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateTrainingConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineInputs(self, request, context):
        """Pipeline Introspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineOutputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineVisualization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inference(self, request, context):
        """Inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """Checkpoint Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CuvisAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CreateSessionRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CreateSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CloseSessionRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CloseSessionResponse.SerializeToString,
            ),
            'Train': grpc.unary_stream_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.TrainRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.TrainResponse.SerializeToString,
            ),
            'GetTrainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainStatus,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainStatusRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainStatusResponse.SerializeToString,
            ),
            'GetTrainingCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingCapabilities,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainingCapabilitiesRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainingCapabilitiesResponse.SerializeToString,
            ),
            'ValidateTrainingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTrainingConfig,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.ValidateTrainingConfigRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.ValidateTrainingConfigResponse.SerializeToString,
            ),
            'GetPipelineInputs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineInputs,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineInputsRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineInputsResponse.SerializeToString,
            ),
            'GetPipelineOutputs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineOutputs,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineOutputsRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineOutputsResponse.SerializeToString,
            ),
            'GetPipelineVisualization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineVisualization,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineVisualizationRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineVisualizationResponse.SerializeToString,
            ),
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.InferenceRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.InferenceResponse.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.SaveCheckpointResponse.SerializeToString,
            ),
            'LoadCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCheckpoint,
                    request_deserializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.LoadCheckpointRequest.FromString,
                    response_serializer=cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.LoadCheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cuvis_ai.v1.CuvisAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cuvis_ai.v1.CuvisAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CuvisAIService(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/CreateSession',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CreateSessionRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/CloseSession',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CloseSessionRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/Train',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.TrainRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/GetTrainStatus',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainStatusRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/GetTrainingCapabilities',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainingCapabilitiesRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetTrainingCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateTrainingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/ValidateTrainingConfig',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.ValidateTrainingConfigRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.ValidateTrainingConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineInputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/GetPipelineInputs',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineInputsRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineInputsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/GetPipelineOutputs',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineOutputsRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineOutputsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineVisualization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/GetPipelineVisualization',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineVisualizationRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.GetPipelineVisualizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/Inference',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.InferenceRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/SaveCheckpoint',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.SaveCheckpointRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.SaveCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cuvis_ai.v1.CuvisAIService/LoadCheckpoint',
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.LoadCheckpointRequest.SerializeToString,
            cuvis__ai_dot_grpc_dot_v1_dot_cuvis__ai__pb2.LoadCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
