plugins:
- cuvis_ai_builtin
- rfdetr_seg
nodes:
- name: DataSource
  class_name: cuvis_ai.node.data.CU3SDataNode
  hparams:
    name: null
- name: Selector
  class_name: cuvis_ai.node.channel_selector.FixedWavelengthSelector
  hparams:
    target_wavelengths:
    - 640.0
    - 550.0
    - 470.0
    normalize_output: true
    norm_mode: per_frame
    apply_gamma: false
    freeze_running_bounds_after_frames: 20
    running_warmup_frames: 10
- name: Seg
  class_name: cuvis_ai_rfdetr.node.rfdetr_segmenter.RFDETRSegmenter
  hparams:
    checkpoint_path: D:/walnuts/walnut_fo_stack/cuvis-ai/cuvis_ai/configs/pipeline/walnut_seg/weights/rgb_full_ema.pth
    variant: large
    threshold: 0.5
    resolution: 504
    tiling: whole
    tile_rows: 405
    row_starts:
    - 0
    - 291
    - 582
    nms_iou: 0.5
    jpeg_roundtrip: false
    jpeg_quality: 95
    class_filter: 0
    score_reduction: max_conf
    top_frac: 0.001
    checkpoint_loader: constructor
connections:
- source: DataSource.outputs.cube
  target: Selector.inputs.cube
- source: DataSource.outputs.wavelengths
  target: Selector.inputs.wavelengths
- source: Selector.outputs.rgb_image
  target: Seg.inputs.rgb_image
metadata:
  name: walnut_seg_rgb_full_cuvisnext_cube
  description: ''
  created: '2026-09-21T15:08:18.702988'
  tags: []
  author: ''
  cuvis_ai_version: 0.17.2
