"""Seed node-catalog assets from cuvis-ai-schemas.

Copies the category SVGs from ``cuvis_ai_schemas/extensions/ui/icons/`` into
``docs/images/node-categories/`` and emits ``docs/stylesheets/node_categories.css``
containing one CSS custom property per category (fill + border) and one per
``NodeTag`` (badge color + short label).

Idempotent. Run before the first ``mkdocs build``; re-run when cuvis-ai-schemas
changes its category palette or tag list.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from cuvis_ai_schemas.enums import NodeCategory
from cuvis_ai_schemas.extensions.ui.node_display import CATEGORY_STYLES, TAG_STYLES

REPO_ROOT = Path(__file__).resolve().parent.parent
ICONS_DST = REPO_ROOT / "docs" / "images" / "node-categories"
CSS_DST = REPO_ROOT / "docs" / "stylesheets" / "node_categories.css"

_SCHEMAS_ICONS = (
    Path(__import__("cuvis_ai_schemas").__file__).parent / "extensions" / "ui" / "icons"
)


def copy_icons() -> int:
    ICONS_DST.mkdir(parents=True, exist_ok=True)
    copied = 0
    for cat in NodeCategory:
        src = _SCHEMAS_ICONS / f"{cat.value}.svg"
        dst = ICONS_DST / f"{cat.value}.svg"
        if not src.exists():
            print(f"  [skip] missing schemas icon: {src}")
            continue
        shutil.copyfile(src, dst)
        copied += 1
    return copied


def emit_css() -> None:
    lines: list[str] = [
        "/* Generated by scripts/_node_catalog_assets.py from cuvis-ai-schemas.",
        "   Do not edit by hand; re-run the helper to refresh. */",
        "",
        ":root {",
    ]
    for cat, style in CATEGORY_STYLES.items():
        lines.append(f"  --node-cat-{cat.value}-fill: {style['fill']};")
        lines.append(f"  --node-cat-{cat.value}-border: {style['border']};")
    for tag, style in TAG_STYLES.items():
        lines.append(f"  --node-tag-{tag.value}-color: {style['badge_color']};")
    lines.append("}")
    lines.append("")
    for tag, _style in TAG_STYLES.items():
        lines.append(
            f'.tag-chip[data-tag="{tag.value}"] {{ '
            f"--chip-color: var(--node-tag-{tag.value}-color); }}"
        )
    lines.append("")
    for cat, _style in CATEGORY_STYLES.items():
        lines.append(
            f'.node-card[data-category="{cat.value}"] {{ '
            f"--card-fill: var(--node-cat-{cat.value}-fill); "
            f"--card-border: var(--node-cat-{cat.value}-border); }}"
        )
        lines.append(
            f'.category-chip[data-category="{cat.value}"] {{ '
            f"--chip-fill: var(--node-cat-{cat.value}-fill); "
            f"--chip-border: var(--node-cat-{cat.value}-border); }}"
        )
    CSS_DST.parent.mkdir(parents=True, exist_ok=True)
    CSS_DST.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    print(f"Copying category icons from {_SCHEMAS_ICONS} -> {ICONS_DST}")
    n = copy_icons()
    print(f"  copied {n}/{len(NodeCategory)} icons")
    print(f"Writing CSS custom properties -> {CSS_DST}")
    emit_css()
    print(f"  wrote {len(CATEGORY_STYLES)} categories, {len(TAG_STYLES)} tags")


if __name__ == "__main__":
    main()
