"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "LentilsAnomalyDataNode",
]

class _LentilsAnomalyDataNodeInputs:
    cube: InputPort
    mask: InputPort

class _LentilsAnomalyDataNodeOutputs:
    wavelengths: OutputPort
    cube: OutputPort
    mask: OutputPort

class LentilsAnomalyDataNode(Node):
    inputs: _LentilsAnomalyDataNodeInputs
    outputs: _LentilsAnomalyDataNodeOutputs
    wavelengths: OutputPort
