"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "BinaryAnomalyLabelMapper",
]

class _BinaryAnomalyLabelMapperInputs:
    cube: InputPort
    mask: InputPort

class _BinaryAnomalyLabelMapperOutputs:
    cube: OutputPort
    mask: OutputPort

class BinaryAnomalyLabelMapper(Node):
    inputs: _BinaryAnomalyLabelMapperInputs
    outputs: _BinaryAnomalyLabelMapperOutputs
    ...
