"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "AnomalyBCEWithLogits",
    "MSEReconstructionLoss",
    "OrthogonalityLoss",
    "SelectorDiversityRegularizer",
    "SelectorEntropyRegularizer",
]

class _AnomalyBCEWithLogitsInputs:
    predictions: InputPort
    targets: InputPort

class _AnomalyBCEWithLogitsOutputs:
    loss: OutputPort

class AnomalyBCEWithLogits(Node):
    inputs: _AnomalyBCEWithLogitsInputs
    outputs: _AnomalyBCEWithLogitsOutputs
    predictions: InputPort
    targets: InputPort
    loss: OutputPort

class _MSEReconstructionLossInputs:
    reconstruction: InputPort
    target: InputPort

class _MSEReconstructionLossOutputs:
    loss: OutputPort

class MSEReconstructionLoss(Node):
    inputs: _MSEReconstructionLossInputs
    outputs: _MSEReconstructionLossOutputs
    reconstruction: InputPort
    target: InputPort
    loss: OutputPort

class _OrthogonalityLossInputs:
    components: InputPort

class _OrthogonalityLossOutputs:
    loss: OutputPort

class OrthogonalityLoss(Node):
    inputs: _OrthogonalityLossInputs
    outputs: _OrthogonalityLossOutputs
    components: InputPort
    loss: OutputPort

class _SelectorDiversityRegularizerInputs:
    weights: InputPort

class _SelectorDiversityRegularizerOutputs:
    loss: OutputPort

class SelectorDiversityRegularizer(Node):
    inputs: _SelectorDiversityRegularizerInputs
    outputs: _SelectorDiversityRegularizerOutputs
    weights: InputPort
    loss: OutputPort

class _SelectorEntropyRegularizerInputs:
    weights: InputPort

class _SelectorEntropyRegularizerOutputs:
    loss: OutputPort

class SelectorEntropyRegularizer(Node):
    inputs: _SelectorEntropyRegularizerInputs
    outputs: _SelectorEntropyRegularizerOutputs
    weights: InputPort
    loss: OutputPort
