"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "AnomalyDetectionMetrics",
    "ComponentOrthogonalityMetric",
    "ExplainedVarianceMetric",
    "ScoreStatisticsMetric",
    "SelectorDiversityMetric",
    "SelectorEntropyMetric",
]

class _AnomalyDetectionMetricsInputs:
    decisions: InputPort
    targets: InputPort

class _AnomalyDetectionMetricsOutputs:
    metrics: OutputPort

class AnomalyDetectionMetrics(Node):
    inputs: _AnomalyDetectionMetricsInputs
    outputs: _AnomalyDetectionMetricsOutputs
    decisions: InputPort
    targets: InputPort
    metrics: OutputPort

class _ComponentOrthogonalityMetricInputs:
    components: InputPort

class _ComponentOrthogonalityMetricOutputs:
    metrics: OutputPort

class ComponentOrthogonalityMetric(Node):
    inputs: _ComponentOrthogonalityMetricInputs
    outputs: _ComponentOrthogonalityMetricOutputs
    components: InputPort
    metrics: OutputPort

class _ExplainedVarianceMetricInputs:
    explained_variance_ratio: InputPort

class _ExplainedVarianceMetricOutputs:
    metrics: OutputPort

class ExplainedVarianceMetric(Node):
    inputs: _ExplainedVarianceMetricInputs
    outputs: _ExplainedVarianceMetricOutputs
    explained_variance_ratio: InputPort
    metrics: OutputPort

class _ScoreStatisticsMetricInputs:
    scores: InputPort

class _ScoreStatisticsMetricOutputs:
    metrics: OutputPort

class ScoreStatisticsMetric(Node):
    inputs: _ScoreStatisticsMetricInputs
    outputs: _ScoreStatisticsMetricOutputs
    scores: InputPort
    metrics: OutputPort

class _SelectorDiversityMetricInputs:
    weights: InputPort

class _SelectorDiversityMetricOutputs:
    metrics: OutputPort

class SelectorDiversityMetric(Node):
    inputs: _SelectorDiversityMetricInputs
    outputs: _SelectorDiversityMetricOutputs
    weights: InputPort
    metrics: OutputPort

class _SelectorEntropyMetricInputs:
    weights: InputPort

class _SelectorEntropyMetricOutputs:
    metrics: OutputPort

class SelectorEntropyMetric(Node):
    inputs: _SelectorEntropyMetricInputs
    outputs: _SelectorEntropyMetricOutputs
    weights: InputPort
    metrics: OutputPort
