"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort

__all__ = [
    "TensorBoardMonitorNode",
]

class _TensorBoardMonitorNodeInputs:
    artifacts: InputPort
    metrics: InputPort

class _TensorBoardMonitorNodeOutputs: ...

class TensorBoardMonitorNode(Node):
    inputs: _TensorBoardMonitorNodeInputs
    outputs: _TensorBoardMonitorNodeOutputs
    artifacts: InputPort
    metrics: InputPort
