"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "IdentityNormalizer",
    "MinMaxNormalizer",
    "SigmoidNormalizer",
    "ZScoreNormalizer",
]

class _IdentityNormalizerInputs:
    data: InputPort

class _IdentityNormalizerOutputs:
    normalized: OutputPort

class IdentityNormalizer(Node):
    inputs: _IdentityNormalizerInputs
    outputs: _IdentityNormalizerOutputs
    data: InputPort
    normalized: OutputPort

class _MinMaxNormalizerInputs:
    data: InputPort

class _MinMaxNormalizerOutputs:
    normalized: OutputPort

class MinMaxNormalizer(Node):
    inputs: _MinMaxNormalizerInputs
    outputs: _MinMaxNormalizerOutputs
    data: InputPort
    normalized: OutputPort

class _SigmoidNormalizerInputs:
    data: InputPort

class _SigmoidNormalizerOutputs:
    normalized: OutputPort

class SigmoidNormalizer(Node):
    inputs: _SigmoidNormalizerInputs
    outputs: _SigmoidNormalizerOutputs
    data: InputPort
    normalized: OutputPort

class _ZScoreNormalizerInputs:
    data: InputPort

class _ZScoreNormalizerOutputs:
    normalized: OutputPort

class ZScoreNormalizer(Node):
    inputs: _ZScoreNormalizerInputs
    outputs: _ZScoreNormalizerOutputs
    data: InputPort
    normalized: OutputPort

class __ScoreNormalizerBaseInputs:
    data: InputPort

class __ScoreNormalizerBaseOutputs:
    normalized: OutputPort

class _ScoreNormalizerBase(Node):
    inputs: __ScoreNormalizerBaseInputs
    outputs: __ScoreNormalizerBaseOutputs
    data: InputPort
    normalized: OutputPort
