"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "TrainablePCA",
]

class _TrainablePCAInputs:
    data: InputPort

class _TrainablePCAOutputs:
    projected: OutputPort
    explained_variance_ratio: OutputPort
    components: OutputPort

class TrainablePCA(Node):
    inputs: _TrainablePCAInputs
    outputs: _TrainablePCAOutputs
    data: InputPort
    projected: OutputPort
    explained_variance_ratio: OutputPort
    components: OutputPort
