"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "SoftChannelSelector",
]

class _SoftChannelSelectorInputs:
    data: InputPort

class _SoftChannelSelectorOutputs:
    selected: OutputPort
    weights: OutputPort

class SoftChannelSelector(Node):
    inputs: _SoftChannelSelectorInputs
    outputs: _SoftChannelSelectorOutputs
    data: InputPort
    selected: OutputPort
    weights: OutputPort
