"""Auto-generated by tools/generate_node_port_stubs.py - do not edit."""

from __future__ import annotations

from cuvis_ai.node.node import Node
from cuvis_ai.pipeline.ports import InputPort, OutputPort

__all__ = [
    "AnomalyMask",
    "PCAVisualization",
]

class _AnomalyMaskInputs:
    decisions: InputPort
    mask: InputPort
    cube: InputPort

class _AnomalyMaskOutputs:
    artifacts: OutputPort

class AnomalyMask(Node):
    inputs: _AnomalyMaskInputs
    outputs: _AnomalyMaskOutputs
    decisions: InputPort
    mask: InputPort
    cube: InputPort
    artifacts: OutputPort

class _PCAVisualizationInputs:
    data: InputPort

class _PCAVisualizationOutputs:
    artifacts: OutputPort

class PCAVisualization(Node):
    inputs: _PCAVisualizationInputs
    outputs: _PCAVisualizationOutputs
    data: InputPort
    artifacts: OutputPort
