# @package _global_


defaults:
- /data@data: lentils
- /training@training: default
- _self_

name: base_trainrun

# Pipeline reference, resolved relative to this trainrun's directory.
pipeline: ../pipeline/anomaly/rx/channel_selector.yaml
output_dir: ./outputs/${name}

training:
  default_root_dir: ${output_dir}
hydra:
  run:
    dir: ${output_dir}
  output_subdir: .hydra
