# @package _global_


defaults:
- /data@data: lentils
- _self_


name: rx_statistical

# Pipeline reference, resolved relative to this trainrun's directory.
pipeline: ../pipeline/anomaly/rx/rx_statistical.yaml

output_dir: outputs/rx_statistical
unfreeze_nodes: []
freeze_nodes: []
metric_nodes:
- metrics_anomaly
loss_nodes: []
